# Generated by Django 5.0 on 2023-12-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='velocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('texts', models.CharField(max_length=250, verbose_name='Описание')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
        ),
    ]
